name: Codspeed Benchmarks

permissions:
  contents: read
  packages: read
  pull-requests: write

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - ".github/workflows/benchmarks.yml"
      - "src"
      - "package.json"
      - "vitest.config.ts"
      - "yarn.lock"

jobs:
  init__node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-node

  benchmarks:
    runs-on: ubuntu-latest
    needs:
      - init__node
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-node

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          run: yarn bench
          token: ${{ secrets.CODSPEED_TOKEN }}
