name: codspeed-benchmarks

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  init__node:
    if: |
      !contains(github.event.pull_request.labels.*.name, 'renovate')
    name: "Initialize: node"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-node

  benchmarks:
    runs-on: ubuntu-latest
    needs:
      - init__node
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-node

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          run: yarn bench
          token: ${{ secrets.CODSPEED_TOKEN }}
